/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 3931d1df2deee56be70fefd9721db5bc)
interface __BaseEnv_Env {
	REQUEST_RATE_LIMITER: RateLimit;
	UPSTREAM_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	PUBLIC_HOSTNAME: "business.newbies.cool";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
