/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: f3923e43fe64c43d45298e2cebccd5c2)
interface __BaseEnv_Env {
	REQUEST_RATE_LIMITER: RateLimit;
	UPSTREAM_RATE_LIMITER: RateLimit;
	SINGAPORE_SOURCE_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	PUBLIC_HOSTNAME: "business.newbies.cool";
	CDP_API_KEY_ID: string;
	CDP_API_KEY_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
